### PR TITLE
[Fix #53] fixing tests issues

### LINKED ISSUE #53: unit tests fail with "{error,{already_started,<0.260.0>}}"
30 of the 31 tests in fiar_server_SUITE fail with {error,{already_started,<0.260.0>}}

It looks like fiar:start() is being called for each test case, and its starting 31 times before the first one has had a chance to stop()

I'm not sure how to fix this. I tried moving it to init_per_suite(), but the test case framework seems to think  init_per_suite() and end_per_suite() are unit tests.

### PR DESCRIPTION
**Pull request by Euen**
[Fix #53] fixing tests issues

### CODE REVIEW

File: src/fiar_notify_users_handler.erl [hunk 1]
```diff
@@ -45,16 +45,16 @@ handle_notify({user_conected, User}, State) ->
   CurrentMatches = fiar:current_matches(User),
   CurrentMatchesJson = fiar_match:matches_to_json(CurrentMatches),
   Response = {[{user, UserJson}, {current_matches, CurrentMatchesJson}]},
-  {send, [{data, jiffy:encode(Response)}, {name, <<"user_connected">>}], State};
+  {send, #{data => jiffy:encode(Response), event => <<"user_connected">>}, State};
```
Comment (gadgetci) [inline src/fiar_notify_users_handler.erl]: According to **Elvis**:
> Line 48 is too long:   {send, #{data => jiffy:encode(Response), event => <<"user_connected">>}, State};.
